# permissions to do edit mykinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mykind-editor-role
rules:
- apiGroups:
  - mygroup.k8s.io
  resources:
  - mykinds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mygroup.k8s.io
  resources:
  - mykinds/status
  verbs:
  - get
  - patch
  - update
